### PR TITLE
Create Morse_Code_Message.rb  filw then added the simple startup Mors…

### PR DESCRIPTION
**Pull request by richie1988**
### Morse Code Message

- Created the file for Morse code 
- Added the Morse  code  letters in the file to be generated

### CODE REVIEW

**Review by lily4178993 — COMMENTED** [review]
Hi @richie1988,
Great work! Could you kindly consider renaming the file from **Morse_Code_Message.rb** to **morse_code_message.rb**? Your assistance is much appreciated.

Thank you.

**Comment by richie1988** [comment]
Hello nelli Thank you kindly consider merging it then Raphael will help
with the rest Thank you

**Comment by lily4178993** [comment]
Please, rename the file to fix the linter error

**Comment by lily4178993** [comment]
Thank you.

**Comment by richie1988** [comment]
> Thank you.

you are welcome Partner

**Pull request merged**
